export default function ObjectsExplanation() {
  return (
    <div className="bg-gray-800 rounded-lg shadow p-6 border border-gray-700 mb-6">
      <h2 className="text-lg font-medium text-white mb-4">
        Location/Objects/Events/...
      </h2>
      <p className="text-sm text-gray-400">
        You can generate QR codes for locations or objects that others can scan
        and associate with posts. Each QR code contains a private key secured by
        public key cryptography and verified through IPFS.
      </p>

      <h3 className="text-md font-medium text-white mt-6 mb-2">
        How does this work?
      </h3>
      <div className="text-sm text-gray-400 mb-4 space-y-2">
        <p>
          The concept can be used in many ways. For example, you can generate a
          QR code for a location or object, which contains a private key. Users
          that are near that QR code can scan it, and the QR code will provide
          them with value used to prove their presence or interaction with that
          location or object.
        </p>
        <p>
          Each QR code can only be generated by the owner of the location or
          object, and it can be used to verify the authenticity of the
          interaction. It can also be time limited, so that it can only be used
          for a specific period of time (producing a new QR code for each period
          to prevent abuse).
        </p>
        <p>
          It can also go in reverse. Your digital identity (DID) can be used to
          generate a short-lived QR code that contains a pairing key. This can
          then be scanned by the creator of the QR code, allowing you to obtain
          a proof of presence from the owner of the location or object. For even
          more security, the proof can be done both ways to provide mutual
          verification.
        </p>
      </div>

      <h3 className="text-md font-medium text-white mb-2">
        Why do we need this?
      </h3>
      <div className="text-sm text-gray-400 mb-4 space-y-2">
        <p>
          The simplest use-case is to verify that a user was present at a
          specific location or interacted with a specific object. This could be
          used for example to collect rewards for checking in at a location, or
          to verify that a user interacted with an object (e.g., a product, a
          piece of art, etc.).
        </p>
        <p>
          But the limits are only your imagination. You can use this to create
          any kind of interaction that is based on proving the presence, for
          example creating a digital twin of a physical objects, providing users
          additional value through information that is related to the object, or
          even creating a digital identity that is tied to a physical object or
          location.
        </p>
      </div>
    </div>
  );
}
